services:
  api:
#    build:
#      context: .
#      dockerfile: Dockerfile
    image: ${IMAGE_URI:-registry.example.com/your-namespace/threads-api}:${IMAGE_TAG:-latest}
    container_name: threads-api

    restart: unless-stopped

    ports:
      - "127.0.0.1:7000:8080"

    env_file:
      - .env

    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ASPNETCORE_URLS: http://+:8080
