services:
  api:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: threads-api

    restart: unless-stopped

    ports:
      - "127.0.0.1:45000:8080"

    env_file:
      - .env

    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ASPNETCORE_URLS: http://+:8080
