<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <Folder Include="Data\Configurations\" />
      <Folder Include="Data\Repositories\Comments\" />
      <Folder Include="Data\Repositories\Follows\" />
      <Folder Include="Data\Repositories\Likes\" />
      <Folder Include="Data\Repositories\Media\" />
      <Folder Include="Data\Repositories\Posts\" />
      <Folder Include="Data\Repositories\RefreshTokens\" />
      <Folder Include="Data\Repositories\Users\" />
      <Folder Include="Security\" />
      <Folder Include="Services\" />
    </ItemGroup>

    <ItemGroup>
      <Compile Update="Data\Repositories\Follows\FollowRepository.cs" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="BCrypt.Net-Next" Version="4.2.0" />
      <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.10" />
      <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.10" />
      <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="10.0.10">
        <PrivateAssets>all</PrivateAssets>
        <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      </PackageReference>
      <PackageReference Include="Microsoft.Extensions.Configuration" Version="10.0.10" />
      <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="10.0.10" />
      <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="10.0.3" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Threads.Application\Threads.Application.csproj" />
    </ItemGroup>

</Project>
