<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <Folder Include="DTOs\Auth\" />
      <Folder Include="DTOs\Comments\" />
      <Folder Include="DTOs\Polls\" />
      <Folder Include="DTOs\Posts\" />
      <Folder Include="DTOs\Users\" />
      <Folder Include="Interfaces\Auth\" />
      <Folder Include="Interfaces\Comments\" />
      <Folder Include="Interfaces\Follows\" />
      <Folder Include="Interfaces\Likes\" />
      <Folder Include="Interfaces\Media\" />
      <Folder Include="Interfaces\Polls\" />
      <Folder Include="Interfaces\Posts\" />
      <Folder Include="Interfaces\Security\" />
      <Folder Include="Interfaces\Users\" />
      <Folder Include="Mapping\" />
      <Folder Include="Services\" />
    </ItemGroup>

    <ItemGroup>
      <Compile Update="DTOs\Polls\PollOptionResponse.cs" />
      <Compile Update="DTOs\Polls\PollResponse.cs" />
      <Compile Update="DTOs\Polls\PollVoteResult.cs" />
      <Compile Update="DTOs\Polls\PollVoteStatus.cs" />
      <Compile Update="DTOs\Polls\VotePollRequest.cs" />
      <Compile Update="Interfaces\Follows\IFollowRepository.cs" />
      <Compile Update="Interfaces\Follows\IFollowService.cs" />
      <Compile Update="Interfaces\Polls\IPollRepository.cs" />
      <Compile Update="Interfaces\Polls\IPollService.cs" />
      <Compile Update="Services\FollowService.cs" />
      <Compile Update="Services\PollService.cs" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Threads.Domain\Threads.Domain.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="AutoMapper" Version="16.2.0" />
    </ItemGroup>

</Project>
