name: Deploy

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to server
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ vars.DEPLOY_HOST }}
          username: ${{ vars.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_SSH_KEY }}

          script: |
            set -e

            cd ~/threads

            git pull --ff-only origin main

            cat > .env <<'EOF'
            ${{ secrets.APP_ENV_FILE }}
            EOF

            docker compose down --remove-orphans
            docker compose up -d --build

            docker compose ps